FROM ubuntu:latest
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y git
RUN apt-get install -y vim
RUN apt-get install -y g++-mingw-w64-x86-64
RUN apt-get install -y python3
RUN git clone https://github.com/primody/Hades.git
WORKDIR /Hades/Hades